services:

  reverseproxy:
    container_name: nginxgateway
    restart: always
    depends_on:
      - identityserver
      - catalog.api
      - basket.api
      - discount.api
      - ordering.api
    ports:
      - "9200:9100"      

  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"
  
  discountdb:
    container_name: discountdb
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=Discountdb
    ports:
      - "5432:5432"
    volumes:
      - postgress_data:/var/lib/postgresql/data/
  
  orderingdb:
    container_name: orderingdb
    restart: always
    environment:
      - SA_PASSWORD=Rahul1234567
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"

  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@eshop.net
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin  

  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8080:8000"
      - "9090:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data 

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672" 
      - "15672:15672"
 
  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSetting__ConnectionString=mongodb://catalogdb:27017"
      - "DatabaseSetting__DatabaseName=CatalogDb"
      - "DatabaseSetting__BrandsCollection=Brands"
      - "DatabaseSetting__TypesCollection=Types"
      - "DatabaseSetting__CollectionName=Products"
    depends_on:
      - catalogdb  
    ports:
      - "9000:80"

  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings__ConnectionString=basketdb:6379"
      - "GrpcSettings__DiscountUrl=http://discount.api"
      - "EventBussSettings__HostAddress=amqp://guest:guest@rabbitmq:5672" 
    depends_on:
      - basketdb
      - rabbitmq 
    ports:
      - "9001:80"
  
  discount.api:
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings__ConnectionString=Host=discountdb;Port=5432;Database=Discountdb;Username=admin;Password=admin1234;TrustServerCertificate=true;SslMode=Disable"
    depends_on:
      - discountdb
    ports:
      - "9002:80"

  ordering.api:
    container_name: ordering.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings__OrderingConnectionString=Server=orderingdb;Database=OrderingDb;User Id=sa;Password=Rahul1234567;TrustServerCertificate=true;"
      - "EventBussSettings__HostAddress=amqp://guest:guest@rabbitmq:5672"
    depends_on:
      - orderingdb 
      - rabbitmq 
    ports:
      - "9003:80"
  
  ocelotapigw:
    container_name: ocelotapigw
    environment:
      - ASPNETCORE_ENVIRONMENT=Development      
    depends_on:
      - catalog.api
      - basket.api
      - discount.api
      - ordering.api
    ports:
      - "9010:80" 

  identityserver:
    container_name: identityserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:9011      
    ports:
      - "9011:9011"